### ISSUE TITLE
[Task] Remove gson in favour of jackson

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat3#101]
Some code carried forward from the old repository included `gson` as a dependency. Elsewhere we also have a dependency on Jackson via Quarkus, and more recently via projectnessie CEL as well. Gson should be dropped and all usages converted to use Jackson instead.

**Comment by andrewazores** [comment]
Upon review, Gson only actually gets pulled in for one usage in an integration test util. Should be very easy to replace. The `pom.xml` already scopes the dependency for test only so this would not affect actual container distributions.

**Comment by lkonno** [comment]
The JvmIdWebRequest uses the graphql to query the jvmId of the targetId, so it seems that it will depend on the graphql endpoint implementation to re-enable this test.

**Comment by andrewazores** [comment]
Thanks for checking on that @lkonno
