### ISSUE TITLE
[Bug] Dependabot PRs request review from both `maintainers` and `reviewers`

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat3#118]
### Current Behavior

Dependabot PRs end up requesting review from both maintainers and reviewers teams.

### Expected Behavior

It should only be maintainers.

### Anything else?

`CODEOWNERS` file defines the files that are "protected" and require `maintainers` review. These are generally the same files/paths that Dependabot may update, so the `.github/dependabot.yml` should not specify reviewers directly.

**Comment by aali309** [comment]
so remove 
` reviewers:
      - "cryostatio/reviewers"`

**Comment by andrewazores** [comment]
Yes, I think that line should be removed from the dependabot config
