### ISSUE TITLE
[Bug] WebSocket connection failure on Chromium browsers

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat3#195]
### Current Behavior

Cannot log in to the cryostat3 application in smoketest when using a Chromium-based browser due to a vague WebSocket error.

### Expected Behavior

Chromium browsers should be able to log in and interact with the web application just fine. Firefox works as expected.

### Anything else?

![Screenshot_2023-11-29_16-34-19](https://github.com/cryostatio/cryostat3/assets/3787464/3d4f047f-2e05-404a-a9cb-55a5693a775e)
![Screenshot_2023-11-29_16-34-09](https://github.com/cryostatio/cryostat3/assets/3787464/4e634f61-4041-4c7d-bbea-a7a8f2f3c081)

**Comment by andrewazores** [comment]
Seems to me like this is working now.

**Comment by grzesuav** [comment]
@andrewazores in which version is this fixed ? I am using latest stable (`2.4.0`) and still getting this

**Comment by andrewazores** [comment]
This was originally filed against early 3.0 development and appears to be fixed. 3.0 will be released on or shortly after July 5th.

**Comment by grzesuav** [comment]
Got it, thanks. Just started exploring version 2.4.0 but have some issues here and there, I will wait for 3.0 release
