### ISSUE TITLE
[Bug] Rule uploads with id failing 

### ISSUE THREAD

**Issue by mwangggg** [cryostatio/cryostat3#261]
### Current Behavior

When trying to upload a rule with id, the rule upload fails with a 500 internal server error.

**Comment by andrewazores** [comment]
`remoteId` or `id`? `remoteId` should only be on [ActiveRecordings](https://github.com/cryostatio/cryostat3/blob/71ab0326b49d81ef124e1937dc69ac1acb20b559/src/main/java/io/cryostat/recordings/ActiveRecording.java#L75), not Rules.

**Comment by mwangggg** [comment]
oh my god I'm so silly
