### ISSUE TITLE
[Request] Restrict Custom Targets domains

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat3#323]
### Describe the feature

Similar to https://github.com/cryostatio/cryostat-agent/issues/242 . The Cryostat 3.0 server allows users to define custom targets. The user can specify any JMX URL and, if it passes a connection check, the server will accept it. This includes targets that are located on untrusted reachable networks, such as on the public internet. The administrative user who deploys Cryostat 3.0 should have a configuration property to control this behaviour, and it should default to a semi-restrictive setting, again similar to what is done in the Agent.

**Comment by andrewazores** [comment]
The `URIRange` from the Agent could probably be extracted out to `-core` so that we can reuse the implementation.

**Comment by andrewazores** [comment]
@mwangggg or @aali309 any interest? I will take it if not.

**Comment by mwangggg** [comment]
I've already got quite a few issues on my plate :/

**Comment by aali309** [comment]
I can try/attempt to do this, when I'm done with graphQL implementing the missing sub-queries.

**Comment by andrewazores** [comment]
This technique should also be applied to discovery plugin registration (in `Discovery.java`).
