### ISSUE TITLE
[Bug] Health check always show report as unavailable

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat3#450]
### Current Behavior

Health endpoint always returns `reportConfigured` and `reportAvailable` as `false`

https://github.com/cryostatio/cryostat3/blob/e5abe7a88b8cd04f31640c282391120c696c1d7e/src/main/java/io/cryostat/Health.java#L75

This seems to be the cause of https://github.com/cryostatio/cryostat-operator/issues/816, which expects those above fields to be `true`.

https://github.com/cryostatio/cryostat-operator/blob/dc5df9bf2950c8f2679f54d2b28fa8e3163ccf20/internal/test/scorecard/types.go#L44

### Expected Behavior

`reportConfigured` and `reportAvailable` should reflect current status of report functionality.

### Anything else?

Is this intentional? Or just a missed TODO?

**Comment by andrewazores** [comment]
Definitely not intentional, seems like just something I forgot to do. Good find!
